"""baseline

Revision ID: 13d0d1c546a3
Revises: 
Create Date: 2026-03-17 14:48:28.299497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d0d1c546a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('accented', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('number_type', sa.String(), nullable=True),
    sa.CheckConstraint("gender IN ('m', 'f', 'n') OR gender IS NULL", name='ck_entries_gender'),
    sa.CheckConstraint("number_type IN ('sg', 'pl', 'both') OR number_type IS NULL", name='ck_entries_number_type'),
    sa.CheckConstraint("pos IN ('noun', 'adjective', 'adverb')", name='ck_entries_pos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accented')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('infinitive', sa.String(), nullable=False),
    sa.Column('accented', sa.String(), nullable=False),
    sa.Column('aspect', sa.String(), nullable=False),
    sa.CheckConstraint("aspect IN ('ipf', 'pf')", name='ck_verbs_aspect'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accented')
    )
    op.create_table('word_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aspect_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipf_verb_id', sa.Integer(), nullable=True),
    sa.Column('pf_verb_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('ipf_verb_id IS NOT NULL OR pf_verb_id IS NOT NULL', name='ck_aspect_pairs_not_both_null'),
    sa.ForeignKeyConstraint(['ipf_verb_id'], ['verbs.id'], ),
    sa.ForeignKeyConstraint(['pf_verb_id'], ['verbs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipf_verb_id', 'pf_verb_id', name='uq_aspect_pairs')
    )
    op.create_table('derivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_verb_id', sa.Integer(), nullable=False),
    sa.Column('derived_verb_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.CheckConstraint("type IS NULL OR type IN ('prefix', 'suffix', 'stem_change', 'stress_change', 'reflexive')", name='ck_derivations_type'),
    sa.ForeignKeyConstraint(['derived_verb_id'], ['verbs.id'], ),
    sa.ForeignKeyConstraint(['source_verb_id'], ['verbs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_verb_id', 'derived_verb_id', name='uq_derivations')
    )
    op.create_table('entry_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verb_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb_id', sa.Integer(), nullable=False),
    sa.Column('tense', sa.String(), nullable=False),
    sa.Column('person', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=False),
    sa.CheckConstraint("gender IS NULL OR gender IN ('masculine', 'feminine', 'neuter')", name='ck_verb_forms_gender'),
    sa.CheckConstraint("number IS NULL OR number IN ('singular', 'plural')", name='ck_verb_forms_number'),
    sa.CheckConstraint("person IS NULL OR person IN ('1', '2', '3')", name='ck_verb_forms_person'),
    sa.CheckConstraint("tense IN ('present', 'future', 'past', 'imperative')", name='ck_verb_forms_tense'),
    sa.ForeignKeyConstraint(['verb_id'], ['verbs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verb_frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb_id', sa.Integer(), nullable=False),
    sa.Column('corpus', sa.String(), nullable=False),
    sa.Column('ipm', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['verb_id'], ['verbs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verb_id', 'corpus', name='uq_verb_frequencies')
    )
    op.create_table('collocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['aspect_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(pos = 'pair' AND pair_id IS NOT NULL) OR (pos != 'pair' AND pair_id IS NULL)", name='ck_lexemes_pair_id_consistent'),
    sa.CheckConstraint("pos IN ('pair', 'noun', 'adjective', 'adverb')", name='ck_lexemes_pos'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pair_id'], ['aspect_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', name='uq_lexemes_entry_id'),
    sa.UniqueConstraint('pair_id', name='uq_lexemes_pair_id')
    )
    op.create_table('pair_tags',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['aspect_pairs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pair_id', 'tag_id')
    )
    op.create_table('pair_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['aspect_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collocation_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collocation_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collocation_id'], ['collocations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_family_members',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['word_families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', 'lexeme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_family_members')
    op.drop_table('collocation_translations')
    op.drop_table('pair_translations')
    op.drop_table('pair_tags')
    op.drop_table('lexemes')
    op.drop_table('collocations')
    op.drop_table('verb_frequencies')
    op.drop_table('verb_forms')
    op.drop_table('entry_forms')
    op.drop_table('derivations')
    op.drop_table('aspect_pairs')
    op.drop_table('word_families')
    op.drop_table('verbs')
    op.drop_table('tags')
    op.drop_table('entries')
    # ### end Alembic commands ###
