"""derivation type and value

Revision ID: fe49726ba0da
Revises: 82a017b243a7
Create Date: 2026-03-07 15:20:26.233999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe49726ba0da'
down_revision: Union[str, Sequence[str], None] = '82a017b243a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('derivation_operations')
    op.add_column('derivations', sa.Column('type', sa.String(), nullable=True))
    op.add_column('derivations', sa.Column('value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('derivations', 'value')
    op.drop_column('derivations', 'type')
    op.create_table('derivation_operations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('derivation_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.CheckConstraint("type IN ('prefix', 'infix', 'suffix', 'stress_change', 'stem_change')", name=op.f('ck_derivation_operations_type')),
    sa.ForeignKeyConstraint(['derivation_id'], ['derivations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_id', 'type', name=op.f('uq_derivation_operations'))
    )
    # ### end Alembic commands ###
